### ISSUE TITLE
Epub opening book but without data

### ISSUE THREAD

**Issue by Tahaylmz** [JideGuru/epub_reader#126]
Issue / Feature -
My issue is 

Platform (android, iOS or both) -
Crash / Error - 
I/sink status(31945): sink is empty
I/SavedLocation(31945): -> savedLocation ->
W/Java7Support(31945): Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
V/FolioActivity(31945): -> initDistractionFreeMode
V/FolioActivity(31945): -> hideSystemUI
V/FolioActivity(31945): -> showSystemUI
W/ark.sesliekita(31945): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/ark.sesliekita(31945): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
V/FolioActivity(31945): -> setDayMode
V/FolioActivity(31945): -> initMediaController
V/FolioActivity(31945): -> setupBook
V/FolioActivity(31945): -> initBook
E/FolioActivity(31945): -> Failed to initialize book
E/FolioActivity(31945): 	at com.folioreader.ui.activity.FolioActivity.initBook(FolioActivity.kt:511)
E/FolioActivity(31945): 	at com.folioreader.ui.activity.FolioActivity.setupBook(FolioActivity.kt:487)
E/FolioActivity(31945): 	at com.folioreader.ui.activity.FolioActivity.onCreate(FolioActivity.kt:301)
E/FolioActivity(31945): 	at android.app.Activity.performCreate(Activity.java:8000)
E/FolioActivity(31945): 	at android.app.Activity.performCreate(Activity.java:7984)
E/FolioActivity(31945): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/FolioActivity(31945): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/FolioActivity(31945): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/FolioActivity(31945): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/FolioActivity(31945): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/FolioActivity(31945): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/FolioActivity(31945): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/FolioActivity(31945): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FolioActivity(31945): 	at android.os.Looper.loop(Looper.java:223)
E/FolioActivity(31945): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/FolioActivity(31945): 	at java.lang.reflect.Method.invoke(Native Method)
E/FolioActivity(31945): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/FolioActivity(31945): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/FolioActivity(31945): Caused by: java.lang.IllegalArgumentException: No enum constant org.readium.r2.shared.Publication.EXTENSION.SESLIEKITAP/FILES/5EDBD229-D335-4B09-82AD-7CA5638FAADF/EPUB/8D9EB99A-D1D0-491A-830B-6FC660478B12
E/FolioActivity(31945): 	at java.lang.Enum.valueOf(Enum.java:257)
E/FolioActivity(31945): 	at org.readium.r2.shared.Publication$EXTENSION.valueOf(Unknown Source:2)
E/FolioActivity(31945): 	at com.folioreader.ui.activity.FolioActivity.initBook(FolioActivity.kt:509)
E/FolioActivity(31945): 	... 17 more
V/FolioActivity(31945): -> onPostCreate
V/FolioActivity(31945): -> onResume

Steps to reproduce / Describe in detail - 
I downloaded url and want to open: encountering this error
![image](https://user-images.githubusercontent.com/45766817/163826052-34f5a0d1-5ef2-48ec-be5e-b61507f62108.png)

**Comment by AkshayJainX** [comment]
Facing the same issue...

**Comment by Tahaylmz** [comment]
I would like to say that it is still not resolved and the error persists. 
Everyone says storage error and doesn't help..

**Comment by pradeepsthapa** [comment]
same error, help

**Comment by Tahaylmz** [comment]
@akshayindia, @pradeepsthapa  is there any progress?

**Comment by pradeepsthapa** [comment]
@akshayindia  rename asset file to short, excluding brackets, worked for me

**Comment by Tahaylmz** [comment]
I solved this problem with the method in the link.

https://stackoverflow.com/questions/72228668/epub-viewer-package-release-build-crash/72290447#72290447
